### ISSUE TITLE
Add live version?

### ISSUE THREAD

**Issue by paf31** [quephird/space-invaders-ps#2]
It would be nice to be able to try this out without having to download and build. Maybe if you commit the generated JS, you could link to it via `rawgit.com` from the README?

Also, once it's finished, maybe we could add it [here](http://www.purescript.org/projects/)?

_Edit_: Nice game by the way :smile:

**Comment by quephird** [comment]
Yeah... I've been told by multiple people that I should have made this happen already. :S And indeed, I was in the midst of doing so on my tilde.town site but I can't log onto the server at the moment. Anyway, for the time being, it's on my personal GitHub page, http://quephird.github.io/games/space-invaders/html/Main.html.

**Comment by quephird** [comment]
And, oh my goodness... thanks for you generous comments. Good grief, I am _nowhere_ near the talent of _real_ game devs. :3

**Comment by paf31** [comment]
Mind if I link to this on purescript.org? It looks to be complete now?

**Comment by quephird** [comment]
Oh my goodness... absolutely!!! I actually have more stuff to add but by all means add the link!!!

**Comment by paf31** [comment]
Cool, thanks, will do :smile:
